---
## Java Open JDK
- name: lhoss.java
  src: git+https://github.com/lhoss/ansible-role-java
  version: remotes/origin/support_configurable_ppa_repos

## Zookeeper
- src: git+https://github.com/teralytics/ansible-zookeeper
  name: teralytics.zookeeper
  version: tags/v0.17.0
