---
- import_tasks: user.yml
  tags: user

- import_tasks: native.yml
  when: hdfs_compile_from_source and inventory_hostname == hdfs_compile_node
  tags: native

- import_tasks: base.yml
  tags: base

- import_tasks: config.yml
  tags: base,config

- import_tasks: datanode.yml
  when: inventory_hostname in hdfs_datanodes
  tags: datanode

- import_tasks: namenode.yml
  when: inventory_hostname in hdfs_namenodes
  tags: namenode

- import_tasks: secondarynamenode.yml
  when: inventory_hostname in hdfs_secondary_namenode and not hdfs_ha_enabled
  tags: secondarynamenode

- import_tasks: journalnode.yml
  when: inventory_hostname in hdfs_journalnodes and hdfs_ha_enabled
  tags: journalnode

- import_tasks: bootstrap_spof.yml
  when: hdfs_bootstrap and not hdfs_ha_enabled
  tags: bootstrap

- import_tasks: bootstrap_ha.yml
  when: hdfs_bootstrap and hdfs_ha_enabled
  tags: bootstrap

- import_tasks: upgrade.yml
  any_errors_fatal: True
  when: hdfs_upgrade
  tags: upgrade
