---
- block:
  - import_tasks: base.yml
  - import_tasks: config.yml
  - import_tasks: namenode.yml
  - name: Restart namenode
    service: name=hdfs-namenode state=restarted
  when:
    - inventory_hostname == hdfs_namenode
    - not hdfs_uptodate
  tags: upgrade_namenode
