---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: hdfs1
    hostname: "{{ item.name }}"
    image: solita/ubuntu-systemd:16.04
    command: /sbin/init
    privileged: True
    groups:
      - namenodes
      - hadoop_hosts
      - journalnodes
      - datanodes
      - zookeeper_hosts
  - name: hdfs2
    hostname: "{{ item.name }}"
    image: solita/ubuntu-systemd:16.04
    command: /sbin/init
    privileged: True
    groups:
      - namenodes
      - hadoop_hosts
      - journalnodes
      - datanodes
      - zookeeper_hosts
  - name: hdfs3
    hostname: "{{ item.name }}"
    image: solita/ubuntu-systemd:16.04
    command: /sbin/init
    privileged: True
    groups:
      - hadoop_hosts
      - journalnodes
      - datanodes
      - zookeeper_hosts
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        java_home: /usr/lib/jvm/java-8-openjdk-amd64
        java_packages:
          - openjdk-8-jdk
        java_openjdk_ppa_repos_support: true

        hdfs_bootstrap: True
        hdfs_ansible_handlers: False
        hdfs_ssh_fence: False
      zookeeper_hosts:
        zookeeper_version: 3.4.8
        zookeeper_client_port: "2181"
        # used by other role defaults (just grep for it)
        zookeeper_hostnames: "{{ groups.zookeeper_hosts | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}"
        # used in the role: ansible-zookeepr
        zookeeper_hosts: "{{ groups.zookeeper_hosts }}"
        zookeeper_register_path_env: true
        zookeeper_debian_apt_install: true
        zookeeper_debian_apt_repositories:
          - repository_url: "ppa:ufscar/zookeeper"
            distro_version: "14.04"

        # custom zookeeper (bin) dir (role default is in /opt )
        zookeeper_dir: /usr/local/zookeeper-{{zookeeper_version}}
        zookeeper_tarball_dir: /tmp/
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
